name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Pabl0vargas
          
          outputs: snake-no-header.svg
          
       
          color_snake: '#0000FF'                    
          color_dots: '#9BE9A8,#40C463,#30A14E,#216E39'                    
          color_bg: '#0D1117'                    
          color_grid: '#161B22'
            
      - name: Push snake animation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          
          # 3. Nos aseguramos de subir el archivo con el nombre correcto
          git add snake-no-header.svg 
          
          git commit -m "chore: generate snake-no-header.svg" || exit 0
          git push
