name: Generate Custom Snake

on:
  # Se ejecuta cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  #  permite ejecutarlo manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Trae el código del repositorio
      - uses: actions/checkout@v3

      # 2. Genera la animación con los colores corregidos
      - uses: Platane/snk@v3
        with:
          github_user_name: Pabl0vargas
          
       
          outputs: |
            dist/snake-generated.svg?color_snake=%230000FF&color_dots=%23161B22,%239BE9A8,%2340C463,%2330A14E,%23216E39&color_bg=%23000000&color_grid=%23161B22

      # 3.  nuevo archivo al repositorio
      - name: Push custom snake
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add dist/snake-generated.svg
          git commit -m "chore: generate custom snake" || exit 0
          git push
